### ISSUE TITLE
Does this work with Flutter Web ?

### ISSUE THREAD

**Issue by joeblew99** [c16a/nats-dart#7]
The readme is not clear because it says Dart web, and may have been written before Flutter Web was an official thing.

I would really appreciate knowing as i am looking at using nats.dart for a project that uses Flutter Web.

**Comment by c16a** [comment]
Flutter web depends heavily on `dart:html`, which doesn't have access to the native TCP socket. So this will NOT work with Flutter web.

**Comment by c16a** [comment]
@joeblew99 Going ahead and closing this. Feel free to reopen if you think this needs to be still looked at.
